# !diagnostics off
soilnonscaled<-MIDWEST_CORN_SOYBEANS_Model2_nonscaled_new
##rescaled farm cost variables to be dollars per acre
soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012_peracre<-(soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012_peracre<-(soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012_peracre<-(soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMVALUE_farmincome_peracre<-(soilnonscaled$FARMVALUE_income_farmsources_gross*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$PAYMENTS_payments_reserve_total_peracre<-(soilnonscaled$PAYMENTS_payments_reserve_total_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_peracre<-(soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012_peracre<-(soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012_peracre<-(soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres
soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012_peracre<-(soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012*1000)/soilnonscaled$AGCENSUS_Cropland_Acres


####reduce skew in dependent variables####
####cover crops
skewness(soilnonscaled$AGCENSUS_Cover_Acres_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Cover_Acres_Ratio)
h<-hist(soilnonscaled$AGCENSUS_Cover_Acres_Ratio)
h
soilnonscaled$AGCENSUS_Cover_Acres_Ratio[soilnonscaled$AGCENSUS_Cover_Acres_Ratio>=1] <- NA
skewness(soilnonscaled$AGCENSUS_Cover_Acres_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Cover_Acres_Ratio)
## to find optimal lambda
lambda = BoxCox.lambda(soilnonscaled$AGCENSUS_Cover_Acres_Ratio)
lambda
## now to transform vector
soilnonscaled$AGCENSUS_Cover_Acres_Ratio_transformed<-BoxCox(soilnonscaled$AGCENSUS_Cover_Acres_Ratio, lambda=0)
skewness(soilnonscaled$AGCENSUS_Cover_Acres_Ratio_transformed, na.rm=T)
summary(soilnonscaled$AGCENSUS_Cover_Acres_Ratio_transformed)
hist(soilnonscaled$AGCENSUS_Cover_Acres_Ratio_transformed)

###no till
skewness(soilnonscaled$AGCENSUS_Notill_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Notill_Ratio)
h<-hist(soilnonscaled$AGCENSUS_Notill_Ratio)
h
soilnonscaled$AGCENSUS_Notill_Ratio[soilnonscaled$AGCENSUS_Notill_Ratio>=.5] <- NA
skewness(soilnonscaled$AGCENSUS_Notill_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Notill_Ratio)
## to find optimal lambda
lambda = BoxCox.lambda(soilnonscaled$AGCENSUS_Notill_Ratio)
lambda
## now to transform vector
soilnonscaled$AGCENSUS_Notill_Ratio_transformed<-BoxCox(soilnonscaled$AGCENSUS_Notill_Ratio, lambda=0)
skewness(soilnonscaled$AGCENSUS_Notill_Ratio_transformed, na.rm=T)
summary(soilnonscaled$AGCENSUS_Notill_Ratio_transformed)
hist(soilscaled$AGCENSUS_Notill_Ratio_transformed)

###multitill
skewness(soilnonscaled$AGCENSUS_Multitill_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Multitill_Ratio)
h<-hist(soilnonscaled$AGCENSUS_Multitill_Ratio)
h
soilnonscaled$AGCENSUS_Multitill_Ratio[soilnonscaled$AGCENSUS_Multitill_Ratio>=.8] <- NA
skewness(soilnonscaled$AGCENSUS_Multitill_Ratio, na.rm=T)
summary(soilnonscaled$AGCENSUS_Multitill_Ratio)
## to find optimal lambda
lambda = BoxCox.lambda(soilnonscaled$AGCENSUS_Multitill_Ratio)
lambda
## now to transform vector
soilnonscaled$AGCENSUS_Multitill_Ratio_transformed<-BoxCox(soilnonscaled$AGCENSUS_Multitill_Ratio, lambda=0)
skewness(soilnonscaled$AGCENSUS_Multitill_Ratio_transformed, na.rm=T)
summary(soilnonscaled$AGCENSUS_Multitill_Ratio_transformed)
hist(soilnonscaled$AGCENSUS_Multitill_Ratio_transformed)
hist(soilscaled$AGCENSUS_Multitill_Ratio_transformed)


##look at distributions and remove outliers
#chemicals
hist(soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012_peracre)
soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012_peracre[soilnonscaled$FARMCOSTS_Chemicals_1000Doll_2012_peracre>=100] <- NA
#rent
hist(soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012_peracre)
summary(soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012_peracre)
soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012_peracre[soilnonscaled$FARMCOSTS_cashrent_land_building_pasture_1000Doll_2012_peracre>=200] <- NA
#fertilizer
hist(soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012_peracre)
soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012_peracre[soilnonscaled$FARMCOSTS_Fert_lime_soilcond_purchased_1000dolls_2012_peracre>=200] <- NA
#feed
hist(soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_FeedExpenses_1000Dolls_2012_peracre>=600] <- NA
#interest
hist(soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_Interest_Expenses_1000Dolls_2012_peracre>=100] <- NA
#fuel
hist(soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_gas_fuel_oil_purchased_1000Dolls_2012_peracre>=120] <- NA
#utilities
hist(soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_Utilities_expenses_1000Dolls_2012_peracre>=60] <- NA
#depreciation
hist(soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012_peracre)
soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012_peracre[soilnonscaled$FARMCOSTS_Depreciation_expenses_1000Doll_2012_peracre>=200] <- NA
#contract labor
hist(soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012_peracre)
summary(soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012_peracre)
soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012_peracre[soilnonscaled$FARMCOSTS_ContractLaborExpense_1000Doll_2012_peracre>=20] <- NA
#property taxes
hist(soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_Property_taxes_paid_1000Dolls_2012_peracre>=60] <- NA
#rent machinery
hist(soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012_peracre)
summary(soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012_peracre)
soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012_peracre[soilnonscaled$FARMCOSTS_rent_lease_machinery_equipment_Expense_1000Dolls_2012_peracre>=20] <- NA
#hauling
hist(soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012_peracre)
summary(soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012_peracre)
soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012_peracre[soilnonscaled$FARMCOSTS_Customwork_hauling_expenses_1000Doll_2012_peracre>=50] <- NA
#net income per acre
hist(soilnonscaled$FARMVALUE_farmincome_peracre)
summary(soilnonscaled$FARMVALUE_farmincome_peracre)
soilnonscaled$FARMVALUE_farmincome_peracre[soilnonscaled$FARMVALUE_farmincome_peracre>=600] <- NA
#reserve program payments
hist(soilnonscaled$PAYMENTS_payments_reserve_total_peracre)
summary(soilnonscaled$PAYMENTS_payments_reserve_total_peracre)
soilnonscaled$PAYMENTS_payments_reserve_total_peracre[soilnonscaled$PAYMENTS_payments_reserve_total_peracre>=200] <- NA
#federal farm program payments
hist(soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_peracre)
summary(soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_peracre)
soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_peracre[soilnonscaled$PAYMENTS_payments_fedfarmprograms_total_peracre>=150] <- NA
#race
hist(soilnonscaled$RACE_Entropy)
summary(soilnonscaled$RACE_Entropy)
#farmvalue
hist(soilnonscaled$FARMVALUE_marketvalue_aveperacre)
summary(soilnonscaled$FARMVALUE_marketvalue_aveperacre)
#look at farm income distribution
hist(soilnonscaled$FARMVALUE_farmincome_peracre)
summary(soilnonscaled$FARMVALUE_farmincome_peracre)
soilnonscaled$FARMVALUE_farmincome_peracre[soilnonscaled$FARMVALUE_farmincome_peracre>=400] <- NA
#save
write.csv(soilnonscaled,"soilnonscaledupdated11_22.csv")
